### ISSUE TITLE
Build error with GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [phile314/tasty-silver#14]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got various errors on tasty-silver (master branch) related to missing instances of `Semigroup` like this:

```
$ cabal install
...
Test/Tasty/Silver/Interactive.hs:296:10: error:
    • No instance for (Semigroup TestOutput)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid TestOutput’
    |
296 | instance Monoid TestOutput where
```

These errors are reported as warnings in GHC 8.0.2/8.2.2 using the `-Wsemigroup` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wsemigroup -Werror'
...
Test/Tasty/Silver/Interactive.hs:296:10: warning: [-Wsemigroup]
    ‘TestOutput’ is an instance of Monoid but not Semigroup.
    This will become an error in a future release.
    |
296 | instance Monoid TestOutput where
    |          ^
```

So, fixing these warnings on GHC 8.0.2/8.2.2 fix the error on GHC 8.4.1-alpha1.

Blocking https://github.com/agda/agda/issues/2878.

**Comment by phile314** [comment]
I have fixed the compat warnings, so hopefully it works with GHC 8.4.1 now. I haven't tested it with GHC 8.4.1 though.

Candidate package is here: https://hackage.haskell.org/package/tasty-silver-3.1.11/candidate

I will make a release after Christmas.

**Comment by asr** [comment]
Modulo some dependencies (see, for example, https://github.com/feuerbach/tasty/issues/196) the candidate compiles with GHC 8.4.1-alpha1.

**Comment by phile314** [comment]
Released: https://hackage.haskell.org/package/tasty-silver-3.1.11

**Comment by asr** [comment]
Thanks for fixing and releasing!
